/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.u1a3_robertchen;

/**
 *
 * @author 335091559
 */
import java.awt.*;
import java.awt.event.*;
import java.util.*;
import javax.swing.*;
public class TilePriceCalculatorApp extends javax.swing.JFrame {

    /**
     * Creates new form TilePrice
     */
    public TilePriceCalculatorApp() {
        initComponents();
        ButtonGroup group = new ButtonGroup();
        group.add(rectangle);
        group.add(parallelogram);
        group.add(triangle);
        group.add(circle);
        group.add(donut);
        group.add(trapezoid);
        group.add(house);
    }
    String dimension1Input, dimension2Input, dimension3Input, dimension4Input, priceInput;
    double dimensionO, dimensionTw, dimensionTh, dimensionF, priceI, length, width;
    int id;
    boolean checkD1, checkD2, checkD3, checkD4;
    ArrayList<Shape> shapes = new ArrayList<Shape>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        rectangle = new javax.swing.JToggleButton();
        parallelogram = new javax.swing.JToggleButton();
        triangle = new javax.swing.JToggleButton();
        circle = new javax.swing.JToggleButton();
        donut = new javax.swing.JToggleButton();
        trapezoid = new javax.swing.JToggleButton();
        house = new javax.swing.JToggleButton();
        title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JTextArea();
        listSubHeading = new javax.swing.JLabel();
        calculate = new javax.swing.JButton();
        totalArea = new javax.swing.JTextField();
        totalAreaPrompt = new javax.swing.JLabel();
        totalCost = new javax.swing.JTextField();
        totalCostPrompt = new javax.swing.JLabel();
        dimension1Prompt = new javax.swing.JLabel();
        dimension2Prompt = new javax.swing.JLabel();
        dimension3Prompt = new javax.swing.JLabel();
        dimension4Prompt = new javax.swing.JLabel();
        pricePrompt = new javax.swing.JLabel();
        dimension1 = new javax.swing.JTextField();
        dimension2 = new javax.swing.JTextField();
        dimension3 = new javax.swing.JTextField();
        dimension4 = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        output = new javax.swing.JTextField();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rectangle.setText("Rectangle");
        rectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectangleActionPerformed(evt);
            }
        });

        parallelogram.setText("Parallelogram");
        parallelogram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parallelogramActionPerformed(evt);
            }
        });

        triangle.setText("Triangle");
        triangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triangleActionPerformed(evt);
            }
        });

        circle.setText("Circle");
        circle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circleActionPerformed(evt);
            }
        });

        donut.setText("Donut");
        donut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donutActionPerformed(evt);
            }
        });

        trapezoid.setText("Trapezoid");
        trapezoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trapezoidActionPerformed(evt);
            }
        });

        house.setText("House");
        house.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                houseActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 204, 0));
        title.setText("Tile Price Calculator");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        list.setEditable(false);
        list.setColumns(20);
        list.setRows(5);
        jScrollPane1.setViewportView(list);

        listSubHeading.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listSubHeading.setText("Tiles in the Floor");

        calculate.setText("Calculate");

        totalArea.setEditable(false);
        totalArea.setEnabled(false);

        totalAreaPrompt.setText("Total Area:");

        totalCost.setEditable(false);
        totalCost.setEnabled(false);

        totalCostPrompt.setText("Total Cost:");

        dimension1Prompt.setText("Dimension 1:");

        dimension2Prompt.setText("Dimension 2:");

        dimension3Prompt.setText("Dimension 3:");

        dimension4Prompt.setText("Dimension 4:");

        pricePrompt.setText("Price per Metre Squared:");

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        remove.setText("Remove");

        output.setEditable(false);

        clear.setText("Clear");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rectangle)
                            .addComponent(trapezoid)
                            .addComponent(parallelogram)
                            .addComponent(circle)
                            .addComponent(donut)
                            .addComponent(triangle, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(house, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dimension2Prompt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dimension2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dimension1Prompt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dimension1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dimension3Prompt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dimension3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dimension4Prompt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dimension4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(remove)
                                    .addComponent(add)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pricePrompt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title)
                        .addGap(121, 121, 121)))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listSubHeading)
                        .addGap(18, 18, 18)
                        .addComponent(clear)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalAreaPrompt)
                            .addComponent(totalCostPrompt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalCost)
                            .addComponent(totalArea, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calculate)
                        .addGap(65, 65, 65))))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(title)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dimension1Prompt)
                                    .addComponent(dimension1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dimension2Prompt)
                                    .addComponent(dimension2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8))
                            .addComponent(add, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dimension3Prompt)
                            .addComponent(dimension3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dimension4Prompt)
                                .addComponent(dimension4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(remove)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pricePrompt)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listSubHeading)
                            .addComponent(clear))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(35, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calculate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(totalArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalAreaPrompt))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(totalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalCostPrompt))
                                .addGap(47, 47, 47))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(rectangle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(parallelogram)
                        .addGap(18, 18, 18)
                        .addComponent(triangle)
                        .addGap(18, 18, 18)
                        .addComponent(circle)
                        .addGap(18, 18, 18)
                        .addComponent(donut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(trapezoid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(house)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectangleActionPerformed
        dimension1Prompt.setText("Length:");
        dimension2Prompt.setText("Width:");
        dimension3Prompt.setText("N/A");
        dimension4Prompt.setText("N/A");
        dimension1.setEnabled(true);
        dimension2.setEnabled(true);
        dimension3.setEnabled(false);
        dimension4.setEnabled(false);
        dimensionTh = 0;
        dimensionF = 0;
        rectangle.setActionCommand("rectangle");
    }//GEN-LAST:event_rectangleActionPerformed

    private void parallelogramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parallelogramActionPerformed
        dimension1Prompt.setText("Base:");
        dimension2Prompt.setText("Height:");
        dimension3Prompt.setText("N/A");
        dimension4Prompt.setText("N/A");
        dimension1.setEnabled(true);
        dimension2.setEnabled(true);
        dimension3.setEnabled(false);
        dimension4.setEnabled(false);
        parallelogram.setActionCommand("parallelogram");
    }//GEN-LAST:event_parallelogramActionPerformed

    private void triangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triangleActionPerformed
        dimension1Prompt.setText("Base:");
        dimension2Prompt.setText("Height:");
        dimension3Prompt.setText("N/A");
        dimension4Prompt.setText("N/A");
        dimension1.setEnabled(true);
        dimension2.setEnabled(true);
        dimension3.setEnabled(false);
        dimension4.setEnabled(false);
        dimensionTh = 0;
        dimensionF = 0;
        triangle.setActionCommand("triangle");
    }//GEN-LAST:event_triangleActionPerformed

    private void circleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circleActionPerformed
        dimension1Prompt.setText("Radius of Inner Circle:");
        dimension2Prompt.setText("N/A");
        dimension3Prompt.setText("N/A");
        dimension4Prompt.setText("N/A");
        dimension1.setEnabled(true);
        dimension2.setEnabled(false);
        dimension3.setEnabled(false);
        dimension4.setEnabled(false);
        dimensionTw = 0;
        dimensionTh = 0;
        dimensionF = 0;
        circle.setActionCommand("circle");
    }//GEN-LAST:event_circleActionPerformed

    private void donutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donutActionPerformed
        dimension1Prompt.setText("Radius of Inner Circle:");
        dimension2Prompt.setText("Radius of Outer Circle:");
        dimension3Prompt.setText("N/A");
        dimension4Prompt.setText("N/A");
        dimension1.setEnabled(true);
        dimension2.setEnabled(true);
        dimension3.setEnabled(false);
        dimension4.setEnabled(false);
        dimensionTh = 0;
        dimensionF = 0;
    }//GEN-LAST:event_donutActionPerformed

    private void trapezoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trapezoidActionPerformed
        dimension1Prompt.setText("Base (a):");
        dimension2Prompt.setText("Base (b):");
        dimension3Prompt.setText("Height:");
        dimension4Prompt.setText("N/A");
        dimension1.setEnabled(true);
        dimension2.setEnabled(true);
        dimension3.setEnabled(true);
        dimension4.setEnabled(false);
        dimensionF = 0;
        trapezoid.setActionCommand("trapezoid");
    }//GEN-LAST:event_trapezoidActionPerformed

    private void houseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_houseActionPerformed
        dimension1Prompt.setText("Base of Roof:");
        dimension2Prompt.setText("Height of Roof:");
        dimension3Prompt.setText("Length of House");
        dimension4Prompt.setText("Width of House");
        dimension1.setEnabled(true);
        dimension2.setEnabled(true);
        dimension3.setEnabled(true);
        dimension4.setEnabled(true);
        house.setActionCommand("house");
    }//GEN-LAST:event_houseActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        dimension1Input = dimension1.getText();
        dimension2Input = dimension2.getText();
        dimension3Input = dimension3.getText();
        dimension4Input = dimension4.getText();
        priceInput = price.getText();
        dimensionO = Integer.parseInt(dimension1Input);
        dimensionTw = Integer.parseInt(dimension2Input);
        dimensionTh = Integer.parseInt(dimension3Input);
        dimensionF = Integer.parseInt(dimension4Input);
        priceI = Integer.parseInt(priceInput);
        
        if (dimension1.isEnabled()) {
            checkD1 = dimension1.getText().isEmpty();
        }
        if (dimension2.isEnabled()) {
            checkD2 = dimension2.getText().isEmpty();
        }
        if (dimension3.isEnabled()) {
            checkD3 = dimension3.getText().isEmpty();
        }
        if (dimension4.isEnabled()) {
            checkD4 = dimension4.getText().isEmpty();
        }
        try {
//            output.setText("");
            id ++;
            if (buttonGroup.getSelection().getActionCommand().equals("rectangle"))  {
                output.setText("test");
                length = dimensionO;
                width = dimensionTw;
                Rectangle rectangle = new Rectangle (length, width, id);
                shapes.add(rectangle);
            } else {
                output.setText("Invalid input. Please enter a positive number.");
            }
//            Shape shape = new Shape(firstN, lastN, annualSalary, year, month,
//                    day, date, id);
//            employees.add(employee);
//            for (int i = 0; i < employees.size(); i++) {
//                output.append(employees.get(i).toString());
//            }
            price.setEnabled(false);
        } catch (Exception e) {
            output.setText("Invalid input. Please enter positive numbers and fill out all "
                    + "required fields.");
        }
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TilePriceCalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TilePriceCalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TilePriceCalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TilePriceCalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TilePriceCalculatorApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton calculate;
    private javax.swing.JToggleButton circle;
    private javax.swing.JButton clear;
    private javax.swing.JTextField dimension1;
    private javax.swing.JLabel dimension1Prompt;
    private javax.swing.JTextField dimension2;
    private javax.swing.JLabel dimension2Prompt;
    private javax.swing.JTextField dimension3;
    private javax.swing.JLabel dimension3Prompt;
    private javax.swing.JTextField dimension4;
    private javax.swing.JLabel dimension4Prompt;
    private javax.swing.JToggleButton donut;
    private javax.swing.JToggleButton house;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea list;
    private javax.swing.JLabel listSubHeading;
    private javax.swing.JTextField output;
    private javax.swing.JToggleButton parallelogram;
    private javax.swing.JTextField price;
    private javax.swing.JLabel pricePrompt;
    private javax.swing.JToggleButton rectangle;
    private javax.swing.JButton remove;
    private javax.swing.JLabel title;
    private javax.swing.JTextField totalArea;
    private javax.swing.JLabel totalAreaPrompt;
    private javax.swing.JTextField totalCost;
    private javax.swing.JLabel totalCostPrompt;
    private javax.swing.JToggleButton trapezoid;
    private javax.swing.JToggleButton triangle;
    // End of variables declaration//GEN-END:variables
}
